create table if not exists public.profiles (
  id uuid primary key,
  display_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Sites authenticates visitors outside Supabase Auth. Keep application profiles
-- independent so stable Sites identities can own private archive rows.
alter table public.profiles drop constraint if exists profiles_id_fkey;

create extension if not exists vector with schema extensions;

create table if not exists public.works (
  id text primary key,
  external_id text,
  title text not null,
  original_title text,
  creator text not null,
  release_year integer,
  media_type text not null,
  poster_url text,
  description text not null default '',
  tags jsonb not null default '[]'::jsonb,
  publishers jsonb not null default '[]'::jsonb,
  edition_verified boolean not null default false,
  source text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.works add column if not exists taste_analysis jsonb;
alter table public.works add column if not exists taste_vector extensions.vector(25);
alter table public.works add column if not exists taste_vector_updated_at timestamptz;
alter table public.works add column if not exists publishers jsonb not null default '[]'::jsonb;
alter table public.works add column if not exists edition_verified boolean not null default false;
alter table public.works add column if not exists canonical_key text;

create table if not exists public.metadata_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  work_id text not null,
  work_title text not null,
  canonical_key text,
  issue_type text not null check (issue_type in ('poster','year','creator','title','media_type','other')),
  current_value text,
  suggested_value text,
  note text,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);
create index if not exists metadata_reports_pending_idx on public.metadata_reports(status, created_at desc);
alter table public.metadata_reports enable row level security;
revoke all on public.metadata_reports from anon, authenticated;
grant all on public.metadata_reports to service_role;

create table if not exists public.archive_items (
  user_id uuid not null references public.profiles(id) on delete cascade,
  work_id text not null references public.works(id) on delete cascade,
  work_json jsonb,
  rating smallint,
  my_comment text not null default '',
  ai_comment text not null default '',
  analysis_status text not null default 'pending',
  analysis_json jsonb,
  archive_state text not null default 'completed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, work_id)
);

alter table public.archive_items add column if not exists rating smallint;
alter table public.archive_items add column if not exists work_json jsonb;
alter table public.archive_items add column if not exists my_comment text not null default '';
alter table public.archive_items add column if not exists ai_comment text not null default '';
alter table public.archive_items add column if not exists analysis_status text not null default 'pending';
alter table public.archive_items add column if not exists analysis_json jsonb;
alter table public.archive_items add column if not exists archive_state text not null default 'completed';
alter table public.archive_items add column if not exists updated_at timestamptz not null default now();
alter table public.archive_items add column if not exists taste_vector extensions.vector(25);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'archive_items_rating_check') then
    alter table public.archive_items add constraint archive_items_rating_check check (rating between 1 and 5);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'archive_items_state_check') then
    alter table public.archive_items add constraint archive_items_state_check check (archive_state in ('completed', 'planned'));
  end if;
end $$;

create table if not exists public.taste_tags (
  user_id uuid not null,
  work_id text not null,
  tag text not null,
  category text not null,
  score double precision not null,
  evidence text,
  engine text not null default 'metadata-lexicon-v1',
  created_at timestamptz not null default now(),
  primary key (user_id, work_id, tag),
  foreign key (user_id, work_id)
    references public.archive_items(user_id, work_id) on delete cascade
);

create table if not exists public.connections (
  user_id uuid not null references public.profiles(id) on delete cascade,
  from_work_id text not null,
  to_work_id text not null,
  connection_type text not null,
  reason text not null,
  score double precision not null,
  shared_tags jsonb not null default '[]'::jsonb,
  work_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, from_work_id, to_work_id, connection_type)
);

create table if not exists public.recommendation_feedback (
  user_id uuid not null references public.profiles(id) on delete cascade,
  from_work_id text not null,
  to_work_id text not null,
  connection_mode text not null,
  value smallint not null check (value in (-1, 1)),
  to_work_title_key text,
  shared_tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, from_work_id, to_work_id, connection_mode)
);

alter table public.recommendation_feedback
  add column if not exists shared_tags jsonb not null default '[]'::jsonb;

alter table public.recommendation_feedback
  add column if not exists to_work_title_key text;

create index if not exists archive_items_user_created_idx
  on public.archive_items (user_id, created_at desc);
create index if not exists archive_items_user_state_idx
  on public.archive_items (user_id, archive_state, updated_at desc);

create index if not exists taste_tags_user_score_idx
  on public.taste_tags (user_id, score desc);

create index if not exists connections_user_source_idx
  on public.connections (user_id, from_work_id, connection_type, score desc);

create index if not exists recommendation_feedback_user_source_idx
  on public.recommendation_feedback (user_id, from_work_id, connection_mode, value);

create index if not exists archive_items_taste_vector_idx
  on public.archive_items using hnsw (taste_vector extensions.vector_cosine_ops);

create index if not exists works_taste_vector_idx
  on public.works using hnsw (taste_vector extensions.vector_cosine_ops);

alter table public.profiles enable row level security;
alter table public.works enable row level security;
alter table public.archive_items enable row level security;
alter table public.taste_tags enable row level security;
alter table public.connections enable row level security;
alter table public.recommendation_feedback enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.works from anon, authenticated;
revoke all on public.archive_items from anon, authenticated;
revoke all on public.taste_tags from anon, authenticated;
revoke all on public.connections from anon, authenticated;
revoke all on public.recommendation_feedback from anon, authenticated;

grant all on public.profiles to service_role;
grant all on public.works to service_role;
grant all on public.archive_items to service_role;
grant all on public.taste_tags to service_role;
grant all on public.connections to service_role;
grant all on public.recommendation_feedback to service_role;

create or replace function public.save_connections(
  p_user_id uuid,
  p_connections jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.connections (
    user_id, from_work_id, to_work_id, connection_type,
    reason, score, shared_tags, work_json
  )
  select
    p_user_id, item->>'from_work_id', item->>'to_work_id', item->>'connection_type',
    item->>'reason', (item->>'score')::double precision,
    coalesce(item->'shared_tags', '[]'::jsonb), item->'work_json'
  from jsonb_array_elements(p_connections) as item
  on conflict (user_id, from_work_id, to_work_id, connection_type) do update set
    reason = excluded.reason,
    score = excluded.score,
    shared_tags = excluded.shared_tags,
    work_json = excluded.work_json,
    updated_at = now();
end;
$$;

revoke all on function public.save_connections(uuid, jsonb) from public, anon, authenticated;
grant execute on function public.save_connections(uuid, jsonb) to service_role;

create or replace function public.backfill_taste_graph(
  p_user_id uuid
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_vectors integer := 0;
  v_connections integer := 0;
begin
  update public.archive_items a
  set taste_vector = (
    select ('[' || string_agg(coalesce((
      select (tag_item->>'score')::double precision
      from jsonb_array_elements(coalesce(a.analysis_json->'tags', '[]'::jsonb)) tag_item
      where tag_item->>'tag' = axis.tag
      limit 1
    ), 0)::text, ',' order by axis.ordinality) || ']')::extensions.vector
    from unnest(array[
      '고독','자아정체성','기억','상실','성장','가족','사랑과 친밀감','인간과 비인간',
      '계급과 불평등','권력과 통제','존재와 죽음','연결의 실패','종말과 재난','미지와 우주',
      '기술과 미래','꿈과 현실','신체와 변형','도시적 고독','공간과 경계','운명과 선택',
      '정의와 죄책감','자연과 인간','멜랑콜리','불안과 공포','유머와 아이러니'
    ]) with ordinality as axis(tag, ordinality)
  )
  where a.user_id = p_user_id
    and a.taste_vector is null
    and jsonb_typeof(a.analysis_json->'tags') = 'array';
  get diagnostics v_vectors = row_count;

  with ranked_pairs as (
    select
      a.user_id,
      a.work_id as from_work_id,
      b.work_id as to_work_id,
      1 - (a.taste_vector <=> b.taste_vector) as score,
      b.work_json,
      coalesce((
        select jsonb_agg(shared.tag order by shared.score desc)
        from (
          select ta.tag, greatest(ta.score, tb.score) as score
          from public.taste_tags ta
          join public.taste_tags tb
            on tb.user_id = ta.user_id and tb.tag = ta.tag and tb.work_id = b.work_id
          where ta.user_id = p_user_id and ta.work_id = a.work_id
          order by greatest(ta.score, tb.score) desc
          limit 3
        ) shared
      ), '[]'::jsonb) as shared_tags
    from public.archive_items a
    join public.archive_items b
      on b.user_id = a.user_id and a.work_id < b.work_id
    where a.user_id = p_user_id
      and a.taste_vector is not null
      and b.taste_vector is not null
    order by a.taste_vector <=> b.taste_vector
    limit 100
  )
  insert into public.connections (
    user_id, from_work_id, to_work_id, connection_type,
    reason, score, shared_tags, work_json
  )
  select
    user_id, from_work_id, to_work_id, 'archive',
    '기존 아카이브에서 Taste DNA 유사도 ' || round((score * 100)::numeric) || '%로 복원된 연결입니다.',
    score, shared_tags, work_json
  from ranked_pairs
  where score > 0
  on conflict (user_id, from_work_id, to_work_id, connection_type) do nothing;
  get diagnostics v_connections = row_count;

  return jsonb_build_object('vectors', v_vectors, 'connections', v_connections, 'version', 1);
end;
$$;

revoke all on function public.backfill_taste_graph(uuid) from public, anon, authenticated;
grant execute on function public.backfill_taste_graph(uuid) to service_role;

create or replace function public.save_archive_analysis(
  p_work jsonb,
  p_item jsonb,
  p_tags jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.works (
    id, external_id, title, original_title, creator, release_year,
    media_type, poster_url, description, tags, publishers, edition_verified, source
  ) values (
    p_work->>'id', p_work->>'external_id', p_work->>'title', p_work->>'original_title',
    p_work->>'creator', (p_work->>'release_year')::integer, p_work->>'media_type',
    p_work->>'poster_url', p_work->>'description', coalesce(p_work->'tags', '[]'::jsonb),
    coalesce(p_work->'publishers', '[]'::jsonb),
    coalesce((p_work->>'edition_verified')::boolean, false),
    p_work->>'source'
  ) on conflict (id) do nothing;

  insert into public.archive_items (
    user_id, work_id, work_json, rating, my_comment, ai_comment, analysis_status, analysis_json, taste_vector
  ) values (
    (p_item->>'user_id')::uuid, p_item->>'work_id', p_item->'work_json', (p_item->>'rating')::smallint,
    coalesce(p_item->>'my_comment', ''), coalesce(p_item->>'ai_comment', ''),
    'complete', p_item->'analysis_json', (p_item->>'taste_vector')::extensions.vector
  ) on conflict (user_id, work_id) do update set
    rating = excluded.rating,
    work_json = excluded.work_json,
    my_comment = excluded.my_comment,
    ai_comment = excluded.ai_comment,
    analysis_status = excluded.analysis_status,
    analysis_json = excluded.analysis_json,
    taste_vector = excluded.taste_vector,
    updated_at = now();

  delete from public.taste_tags
    where user_id = (p_item->>'user_id')::uuid and work_id = p_item->>'work_id';

  insert into public.taste_tags (user_id, work_id, tag, category, score, evidence, engine)
  select distinct on (tag->>'tag')
    (tag->>'user_id')::uuid, tag->>'work_id', tag->>'tag', tag->>'category',
    (tag->>'score')::double precision, tag->>'evidence', tag->>'engine'
  from jsonb_array_elements(p_tags) as tag
  order by tag->>'tag';
end;
$$;

revoke all on function public.save_archive_analysis(jsonb, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.save_archive_analysis(jsonb, jsonb, jsonb) to service_role;

create or replace function public.taste_similarity_edges(
  p_user_id uuid,
  p_limit integer default 24
) returns table (
  source_work_id text,
  target_work_id text,
  similarity double precision
)
language sql
security definer
set search_path = public, extensions
stable
as $$
  select
    a.work_id as source_work_id,
    b.work_id as target_work_id,
    1 - (a.taste_vector <=> b.taste_vector) as similarity
  from public.archive_items a
  join public.archive_items b
    on a.user_id = b.user_id and a.work_id < b.work_id
  where a.user_id = p_user_id
    and a.taste_vector is not null
    and b.taste_vector is not null
  order by a.taste_vector <=> b.taste_vector
  limit greatest(1, least(coalesce(p_limit, 24), 100));
$$;

revoke all on function public.taste_similarity_edges(uuid, integer) from public, anon, authenticated;
grant execute on function public.taste_similarity_edges(uuid, integer) to service_role;

create or replace function public.upsert_work_catalog(
  p_works jsonb
) returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_count integer := 0;
begin
  insert into public.works (
    id, external_id, title, original_title, creator, release_year,
    media_type, poster_url, description, tags, publishers, edition_verified, source,
    taste_analysis, taste_vector, taste_vector_updated_at
  )
  select
    item->>'id', nullif(item->>'external_id', ''), item->>'title',
    nullif(item->>'original_title', ''), item->>'creator',
    nullif(item->>'release_year', '')::integer, item->>'media_type',
    nullif(item->>'poster_url', ''), coalesce(item->>'description', ''),
    coalesce(item->'tags', '[]'::jsonb), coalesce(item->'publishers', '[]'::jsonb), coalesce((item->>'edition_verified')::boolean, false), coalesce(item->>'source', 'Taste Constellation'),
    item->'taste_analysis', (item->>'taste_vector')::extensions.vector, now()
  from jsonb_array_elements(coalesce(p_works, '[]'::jsonb)) as item
  where nullif(item->>'id', '') is not null
    and nullif(item->>'title', '') is not null
  on conflict (id) do update set
    external_id = coalesce(works.external_id, nullif(excluded.external_id, '')),
    original_title = coalesce(works.original_title, nullif(excluded.original_title, '')),
    creator = case when works.creator is null or works.creator = '작자 미상' then excluded.creator else works.creator end,
    release_year = coalesce(works.release_year, excluded.release_year),
    media_type = case when works.media_type = 'OTHER' then excluded.media_type else works.media_type end,
    poster_url = coalesce(works.poster_url, excluded.poster_url),
    description = case when length(excluded.description) > length(works.description) then excluded.description else works.description end,
    tags = case when jsonb_array_length(excluded.tags) > jsonb_array_length(works.tags) then excluded.tags else works.tags end,
    publishers = case when jsonb_array_length(excluded.publishers) > jsonb_array_length(works.publishers) then excluded.publishers else works.publishers end,
    edition_verified = works.edition_verified or excluded.edition_verified,
    taste_analysis = excluded.taste_analysis,
    taste_vector = excluded.taste_vector,
    taste_vector_updated_at = now(),
    updated_at = now();
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.upsert_work_catalog(jsonb) from public, anon, authenticated;
grant execute on function public.upsert_work_catalog(jsonb) to service_role;

create or replace function public.match_work_catalog(
  p_query extensions.vector(25),
  p_excluded text[] default array[]::text[],
  p_limit integer default 48
) returns table (
  id text,
  external_id text,
  title text,
  original_title text,
  creator text,
  release_year integer,
  media_type text,
  poster_url text,
  description text,
  tags jsonb,
  publishers jsonb,
  edition_verified boolean,
  source text,
  taste_analysis jsonb,
  similarity double precision
)
language sql
security definer
set search_path = public, extensions
stable
as $$
  select
    w.id, w.external_id, w.title, w.original_title, w.creator, w.release_year,
    w.media_type, w.poster_url, w.description, w.tags, w.publishers, w.edition_verified, w.source, w.taste_analysis,
    1 - (w.taste_vector <=> p_query) as similarity
  from public.works w
  where w.taste_vector is not null
    and not (w.id = any(coalesce(p_excluded, array[]::text[])))
  order by w.taste_vector <=> p_query
  limit greatest(1, least(coalesce(p_limit, 48), 100));
$$;

revoke all on function public.match_work_catalog(extensions.vector, text[], integer) from public, anon, authenticated;
grant execute on function public.match_work_catalog(extensions.vector, text[], integer) to service_role;
