create table if not exists public.metadata_changes (
  id bigint generated by default as identity primary key,
  report_id bigint references public.metadata_reports(id) on delete set null,
  work_id text not null,
  work_title text not null,
  field_name text not null check (field_name in ('poster_url','release_year','creator','title','media_type')),
  previous_value jsonb,
  new_value jsonb,
  status text not null default 'applying' check (status in ('applying','applied','rolled_back')),
  changed_by text not null,
  changed_at timestamptz not null default now(),
  rolled_back_by text,
  rolled_back_at timestamptz,
  rollback_note text
);
create index if not exists metadata_changes_work_idx on public.metadata_changes(work_id, changed_at desc);
alter table public.metadata_changes enable row level security;
revoke all on public.metadata_changes from anon, authenticated;
grant all on public.metadata_changes to service_role;
