alter table public.works add column if not exists canonical_key text;

create table if not exists public.metadata_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  work_id text not null,
  work_title text not null,
  canonical_key text,
  issue_type text not null check (issue_type in ('poster','year','creator','title','media_type','other')),
  current_value text,
  suggested_value text,
  note text,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists metadata_reports_pending_idx
  on public.metadata_reports(status, created_at desc);

alter table public.metadata_reports enable row level security;
revoke all on public.metadata_reports from anon, authenticated;
grant all on public.metadata_reports to service_role;
