const works={
 evangelion:{externalId:'30',title:'신세기 에반게리온',creator:'안노 히데아키',type:'ANIME',year:'1995',award:'🏆 Seiun',quote:'“고슴도치의 딜레마를 세계의 종말까지 밀어붙인 작품.”',tags:['고독','자아정체성','부모와 자식','종말'],score:94,posterUrl:'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx30-AI1zr74Dh4ye.jpg',artwork:{source:'AniList',kind:'official-cover',selection:'공식 고해상도 대표 커버'},poster:'poster-eva',posterText:'NEON<br>GENESIS<br><b>EVANGELION</b>'},
 parasite:{externalId:'496243',title:'기생충',creator:'봉준호',type:'FILM',year:'2019',award:'🏆 Cannes · Oscar',quote:'“위로 올라가고 싶은 욕망을 한 채의 집으로 압축한 비극.”',tags:['계급','공간','상승 욕망','침입'],score:91,poster:'poster-parasite',posterText:'PARA<br><b>SITE</b>'},
 her:{externalId:'152601',title:'Her',creator:'스파이크 존즈',type:'FILM',year:'2013',award:'🏆 Academy',quote:'“가장 가까운 존재가 몸이 없을 때, 사랑은 무엇으로 남는가.”',tags:['외로움','인간과 비인간','친밀감','상실'],score:88,poster:'poster-her',posterText:'A SPIKE JONZE<br><b>HER</b>'}
};
const recs={
 evangelion:{deep:[['BOOK','노르웨이의 숲','무라카미 하루키','누군가와 연결되고 싶지만 연결되는 법을 모른다는 점에서 닮았다.'],['FILM','시네도키, 뉴욕','찰리 카우프먼','자신의 내면을 세계 전체로 확장한다는 점에서 연결된다.'],['ANIME','Serial Experiments Lain','나카무라 류타로','자아와 타인의 경계가 붕괴하는 지점까지 나아간다.']],story:[['FILM','멜랑콜리아','라스 폰 트리에','개인의 우울과 세계의 종말이 같은 궤도 위에 놓인다.','Melancholia'],['BOOK','유년기의 끝','아서 C. 클라크','인류의 진화가 곧 지금의 인간과의 작별이 된다.',"Childhood's End"],['ANIME','건버스터','안노 히데아키','거대한 재난과 한 소녀의 성장을 함께 밀어붙인다.','Top wo Nerae! Gunbuster']],mood:[['FILM','릴리 슈슈의 모든 것','이와이 슌지','청춘의 고립을 차갑고 아름다운 감각으로 붙든다.'],['BOOK','인간 실격','다자이 오사무','타인 속에서 자신을 연기하는 존재의 피로가 닮았다.'],['GAME','SIGNALIS','rose-engine','고립, 신체, 기억이 붕괴하는 정서를 공유한다.']],idea:[['BOOK','고독한 군중','데이비드 리스먼','타인과 함께 있으면서도 고립되는 현대인의 역설을 읽는다.'],['FILM','퍼소나','잉마르 베리만','나와 타인의 얼굴이 어디서 갈라지는지 묻는다.'],['MANGA','오야스미 푼푼','아사노 이니오','성장이 구원이 아니라 더 복잡한 고립이 되는 이야기다.']],visual:[['FILM','2001: 스페이스 오디세이','스탠리 큐브릭','기하학적 공간과 압도적 스케일로 인간을 작게 만든다.'],['ANIME','천사의 알','오시이 마모루','설명보다 상징과 침묵으로 종말의 풍경을 만든다.'],['FILM','더 폴','타셈 싱','강렬한 색과 구도로 내면의 균열을 시각화한다.']]},
 parasite:{deep:[['BOOK','위대한 개츠비','F. 스콧 피츠제럴드','두 작품 모두 위로 올라가고 싶은 욕망을 공간으로 표현한다.'],['FILM','하이-라이즈','벤 웨틀리','한 건물의 수직 구조가 계급 질서를 그대로 드러낸다.'],['MANGA','도박묵시록 카이지','후쿠모토 노부유키','가난이 인간을 선택지가 없는 게임에 밀어 넣는다.']],story:[['FILM','어스','조던 필','닮은 두 가족의 충돌로 억눌린 계층을 수면 위로 끌어낸다.'],['BOOK','하녀','프리다 맥파든','타인의 집에 들어온 사람이 질서를 뒤집는다.'],['ANIME','도쿄 갓파더즈','곤 사토시','도시 변두리의 인물들이 우연과 생존으로 엮인다.']]},
 her:{deep:[['BOOK','클라라와 태양','가즈오 이시구로','비인간 존재의 헌신을 통해 인간의 사랑을 되비춘다.'],['ANIME','공각기동대','오시이 마모루','몸을 벗어난 정신도 한 인간으로 사랑받을 수 있는지 묻는다.'],['FILM','로스트 인 트랜슬레이션','소피아 코폴라','잠시 연결된 두 사람이 외로움을 견디는 방식이 닮았다.']]}
};
let current='evangelion', mode='deep';
let searchTimer=0, searchController=null, recommendationController=null, recommendationCache=new Map, culturalContextCache=new Map, publisherCache=new Map, editorialCache=new Map, artworkCache=new Map;
let archive=[], archiveReady=false, archiveError='', tasteProfile={tags:[],statement:''}, similarityEdges=[], connectionGraph=[], constellationGraph=null, graphFilter='all', archiveQuery='', archiveType='all', archiveState='all', archiveSort='updated', selectedRating=5, toastTimer=0;
let installPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const safeUrl=value=>{if(!value)return'';try{const u=new URL(String(value),location.origin);return u.protocol==='http:'||u.protocol==='https:'?u.href:''}catch{return''}};
function setSearchOpen(open){$('#searchResults').hidden=!open;$('#searchInput').setAttribute('aria-expanded',String(open))}
function updateConnectionStatus(){const status=$('#connectionStatus');if(!status)return;status.hidden=navigator.onLine;document.documentElement.classList.toggle('is-offline',!navigator.onLine)}
async function installApp(){if(!installPrompt){toast('공유 버튼을 누른 뒤 ‘홈 화면에 추가’를 선택하세요.');return}const prompt=installPrompt;installPrompt=null;$('#installApp').hidden=true;await prompt.prompt();const choice=await prompt.userChoice;if(choice.outcome==='accepted')toast('취향 성좌를 홈 화면에 설치했어요.')}
function enableAppShell(){const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true,isIos=/iphone|ipad|ipod/i.test(navigator.userAgent);updateConnectionStatus();if(isIos&&!standalone)$('#installApp').hidden=false;addEventListener('online',()=>{updateConnectionStatus();toast('연결이 복구됐어요.')});addEventListener('offline',updateConnectionStatus);addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installApp').hidden=false});addEventListener('appinstalled',()=>{installPrompt=null;$('#installApp').hidden=true});$('#installApp').onclick=installApp;if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}))}
const AWARD_CONTEXT={'신세기에반게리온':['Seiun Award','Animation Kobe Award','Nihon SF Taisho','Japan Media Arts Festival Excellence Award'],'기생충':['Cannes Palme d’Or','Academy Best Picture'],'her':['Academy'],'듄':['Hugo','Nebula'],'dune':['Hugo','Nebula'],'어둠의왼손':['Hugo','Nebula'],'thelefthandofdarkness':['Hugo','Nebula'],'한밤의아이들':['Booker'],'midnightschildren':['Booker']};
const NAMU_DOCUMENTS={'신세기에반게리온':'신세기 에반게리온'};
const titleKey=value=>String(value||'').normalize('NFKC').toLowerCase().replace(/[^a-z0-9가-힣]/g,'');
function bridgeProfile(w){const tags=(w.analysis?.tags?.map(item=>item.tag)||w.tags||[]).map(String),text=[w.title,w.originalTitle,w.description,...tags].join(' ').toLowerCase(),has=words=>words.some(word=>text.includes(word)),type=w.type||w.mediaType||'OTHER',axes={Cinema:type==='FILM'||type==='TV'?94:42+(has(['시각','공간','도시','visual','cinema'])?30:0),Literature:type==='BOOK'?94:44+(has(['서사','기억','성장','story','문학'])?28:0),Anime:type==='ANIME'?94:38+(has(['정체성','기술','신체','꿈','anime'])?30:0),Philosophy:40+(has(['정체성','존재','인간','기억','철학','identity','existence'])?42:0)},wikiAwards=(w.wikidata?.awards||[]).map(item=>item.label).filter(Boolean),awards=wikiAwards.length?wikiAwards:(AWARD_CONTEXT[titleKey(w.title)]||String(w.award||'').replace(/^🏆\s*/,'').split(' · ').filter(Boolean)),countries=(w.wikidata?.countries||[]).map(item=>item.label).filter(Boolean),scriptBridge=/[가-힣ぁ-んァ-ン一-龯]/.test(String(w.originalTitle||''))&&/[a-z]/i.test(String(w.title||'')),culture=Math.min(96,48+(scriptBridge?24:0)+(w.source&&w.source!=='Taste Constellation'?10:0)+(awards.length?8:0)+(countries.length?8:0)),values=[...Object.values(axes),culture],score=Math.min(98,Math.round(values.reduce((a,b)=>a+b,0)/values.length+Math.min(8,awards.length*3))),top=Object.entries(axes).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([name])=>name),origin=countries.length?`${countries.join('·')} 문화권에서 출발해 `:'',context=scriptBridge?`${origin}${top.join('와 ')}를 잇고, 서로 다른 언어권을 건너는 작품입니다.`:`${origin}${top.join('와 ')} 사이에서 취향의 통로가 되는 작품입니다.`;return{score,axes,culture,awards,countries,context}}
function paintBridgeContext(w){const profile=bridgeProfile(w),namuDocument=NAMU_DOCUMENTS[titleKey(w.title)]||w.title||'',namuUrl=`https://namu.wiki/w/${encodeURIComponent(namuDocument)}`,curated=AWARD_CONTEXT[titleKey(w.title)]||[];profile.awards=[...new Set([...profile.awards,...curated])];$('#bridgeScore').textContent=profile.score;$('#bridgeMeter').style.width=profile.score+'%';$('#bridgeAxes').innerHTML=Object.entries(profile.axes).map(([name,value])=>`<span><b>${esc(name)}</b><i style="width:${value}%"></i><em>${value}</em></span>`).join('');$('#cultureContext').textContent=profile.context;const awards=profile.awards.map(name=>`<span>🏆 ${esc(name)}</span>`),countries=profile.countries.map(name=>`<span>🌐 ${esc(name)}</span>`),source=w.title?`<a href="${esc(namuUrl)}" target="_blank" rel="noopener noreferrer">나무위키 작품 정보 ↗</a>`:'';$('#awardContext').innerHTML=awards.length||countries.length?[...awards,...countries,source].join(''):'<small>확인된 주요 수상·국가 정보가 없습니다.</small>';return profile}
async function loadCulturalContext(id,w){if(w.wikidata?.matched&&w.wikidata.catalogVersion===2)return;if(culturalContextCache.has(id)){await culturalContextCache.get(id);return}const params=new URLSearchParams({title:w.title||'',originalTitle:w.originalTitle||'',year:w.year||'',mediaType:w.type||w.mediaType||'OTHER'}),job=fetch(`/api/cultural-context?${params}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'Wikidata');if(data.matched){works[id].wikidata=data;if(current===id){const bridge=paintBridgeContext(works[id]);$('.award').textContent=bridge.awards.length?`🏆 ${bridge.awards.join(' · ')}`:works[id].source||''}if(archive.includes(id))paintBridgeWork()}return data}).catch(()=>null);culturalContextCache.set(id,job);await job}
function paintPublishers(w){const box=$('#publisherContext'),type=w.type||w.mediaType||'OTHER';if(type!=='BOOK'){box.hidden=true;box.innerHTML='';return}const publishers=(w.publishers||[]).map(item=>typeof item==='string'?item:item.name).filter(Boolean);box.hidden=false;box.innerHTML=publishers.length?`<strong>한국어판 출판사</strong><div>${publishers.map(name=>`<span>▣ ${esc(name)}</span>`).join('')}</div><small>Google Books·Open Library에서 확인된 판본</small>`:'<small>한국어판 출판사 정보를 확인하고 있습니다.</small>'}
async function loadBookPublishers(id,w){const type=w.type||w.mediaType||'OTHER';if(type!=='BOOK'||w._publishersLoaded)return;if(publisherCache.has(id)){await publisherCache.get(id);return}const params=new URLSearchParams({title:w.title||'',creator:w.creator||''}),job=fetch(`/api/book-publishers?${params}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'publishers');works[id].publishers=data.publishers||[];works[id]._publishersLoaded=true;if(current===id)paintPublishers(works[id]);return data}).catch(()=>{works[id]._publishersLoaded=true;if(current===id)paintPublishers(works[id]);return null});publisherCache.set(id,job);await job}
async function loadEditorialIntro(id,w){if(w.quote||w.editorialIntro)return;if(editorialCache.has(id)){await editorialCache.get(id);return}const job=fetch('/api/editorial-intro',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({work:{...w,id}})}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'editorial');if(data.text){works[id].editorialIntro=data.text;if(current===id&&!works[id].quote)$('#workQuote').textContent=`“${data.text}”`}return data}).catch(()=>null);editorialCache.set(id,job);await job}
const compatibleMedia=(wanted,item)=>item.mediaType===wanted||(wanted==='BOOK'&&item.mediaType==='MANGA')||(wanted==='MANGA'&&item.mediaType==='BOOK')||(wanted==='ANIME'&&item.mediaType==='TV');
function bestMetadataMatch(items,w){const normalized=value=>String(value||'').normalize('NFKC').toLowerCase().replace(/[^a-z0-9가-힣]/g,''),titles=[w.title,w.originalTitle].map(normalized).filter(Boolean),creator=normalized(w.creator),wantedYear=Number(w.year)||0,compatible=(items||[]).filter(item=>compatibleMedia(w.mediaType||w.type||'OTHER',item)),ranked=compatible.map(item=>{const aliases=[item.title,item.originalTitle,...(item.identityAliases||[])].map(normalized).filter(Boolean),itemCreator=normalized(item.creator),exact=titles.some(value=>aliases.includes(value)),creatorMatch=creator&&itemCreator&&(creator.includes(itemCreator)||itemCreator.includes(creator)),itemYear=Number(item.year)||0,yearDistance=wantedYear&&itemYear?Math.abs(wantedYear-itemYear):null,yearScore=yearDistance===0?35:yearDistance===1?12:yearDistance===null?0:-Math.min(120,yearDistance*18);return{item,score:(exact?100:0)+(creatorMatch?25:0)+yearScore+(item.posterUrl?4:0),yearDistance}}).filter(match=>!(wantedYear&&match.yearDistance!==null&&match.yearDistance>1&&!creator)).sort((a,b)=>b.score-a.score)[0];return ranked&&ranked.score>=20?ranked.item:null}

function openMetadataReport(){const w=works[current];$('#metadataReportTitle').textContent=`${w.title} 정보 오류 신고`;$('#metadataIssueType').value='poster';$('#metadataSuggestedValue').value='';$('#metadataReportNote').value='';$('#metadataReportDialog').showModal()}
async function submitMetadataReport(){const button=$('#submitMetadataReport');button.disabled=true;button.textContent='접수 중…';try{const r=await fetch('/api/metadata-reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({work:{...works[current],id:current},issueType:$('#metadataIssueType').value,suggestedValue:$('#metadataSuggestedValue').value,note:$('#metadataReportNote').value})}),data=await r.json();if(!r.ok)throw new Error(data.error||'신고를 접수하지 못했습니다.');$('#metadataReportDialog').close();toast('정보 수정 제안을 접수했어요. 검토 후 반영됩니다.')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='수정 제안 보내기'}}

const metadataIssueLabels={poster:'포스터·표지',year:'발표 연도',creator:'창작자',title:'작품 제목',media_type:'매체 구분',other:'기타'};
async function loadMetadataReviewQueue(open=false){try{const r=await fetch('/api/metadata-reports'),data=await r.json();if(r.status===403||r.status===401)return;if(!r.ok)throw new Error(data.error||'검수 목록을 불러오지 못했습니다.');$('#metadataReviewBtn').hidden=false;$('#metadataReviewCount').textContent=data.count||0;$('#metadataReviewList').innerHTML=data.items.length?data.items.map(item=>`<article class="metadata-review-item" data-report-id="${item.id}"><header><strong>${esc(item.work_title)}</strong><span>${esc(metadataIssueLabels[item.issue_type]||item.issue_type)}</span></header><dl><dt>현재</dt><dd>${esc(item.current_value||'정보 없음')}</dd><dt>제안</dt><dd>${esc(item.suggested_value||'직접 확인 필요')}</dd></dl>${item.note?`<p>${esc(item.note)}</p>`:''}<label>검수 메모<input data-resolution-note maxlength="2000" placeholder="승인·반려 근거(선택)" /></label><div><button type="button" data-review-decision="rejected">반려</button><button type="button" data-review-decision="accepted">승인·반영</button></div></article>`).join(''):'<p class="review-empty">대기 중인 수정 제안이 없습니다.</p>';if(open)$('#metadataReviewDialog').showModal()}catch(error){if(open)toast(error.message)}}
async function reviewMetadata(button){const item=button.closest('[data-report-id]'),decision=button.dataset.reviewDecision,note=item.querySelector('[data-resolution-note]').value;button.disabled=true;try{const r=await fetch(`/api/metadata-reports/${item.dataset.reportId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({decision,resolutionNote:note})}),data=await r.json();if(!r.ok)throw new Error(data.error||'검수 결과를 저장하지 못했습니다.');await loadMetadataReviewQueue();toast(decision==='accepted'?'작품 정보를 승인하고 반영했어요.':'수정 제안을 반려했어요.')}catch(error){toast(error.message)}finally{button.disabled=false}}
const metadataFieldLabels={poster_url:'포스터·표지',release_year:'발표 연도',creator:'창작자',title:'작품 제목',media_type:'매체 구분'};
const metadataValue=value=>value===null||value===undefined||value===''?'정보 없음':String(value);
async function loadMetadataChangeHistory(){try{const r=await fetch('/api/metadata-changes'),data=await r.json();if(r.status===403||r.status===401)return;if(!r.ok)throw new Error(data.error||'변경 이력을 불러오지 못했습니다.');$('#metadataChangeList').innerHTML=data.items.length?data.items.map(item=>`<article class="metadata-review-item metadata-change-item" data-change-id="${item.id}"><header><strong>${esc(item.work_title)}</strong><span>${esc(metadataFieldLabels[item.field_name]||item.field_name)}</span></header><dl><dt>변경 전</dt><dd>${esc(metadataValue(item.previous_value))}</dd><dt>변경 후</dt><dd>${esc(metadataValue(item.new_value))}</dd></dl><p>${new Date(item.changed_at).toLocaleString('ko-KR')} · ${item.status==='rolled_back'?'되돌림 완료':'반영됨'}</p>${item.status==='applied'?`<label>되돌림 메모<input data-rollback-note maxlength="2000" placeholder="되돌리는 이유(선택)" /></label><div><button type="button" data-rollback-change>이 변경 되돌리기</button></div>`:''}</article>`).join(''):'<p class="review-empty">아직 반영된 변경 이력이 없습니다.</p>'}catch(error){$('#metadataChangeList').innerHTML=`<p class="review-empty">${esc(error.message)}</p>`}}
async function rollbackMetadata(button){const item=button.closest('[data-change-id]'),note=item.querySelector('[data-rollback-note]').value;if(!confirm('이 변경 전 값으로 복구할까요? 공용 작품 정보와 저장된 성좌에 함께 반영됩니다.'))return;button.disabled=true;try{const r=await fetch(`/api/metadata-changes/${item.dataset.changeId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({note})}),data=await r.json();if(!r.ok)throw new Error(data.error||'변경을 되돌리지 못했습니다.');await Promise.all([loadMetadataChangeHistory(),loadMetadataReviewQueue()]);toast('작품 정보를 변경 전 값으로 복구했어요.')}catch(error){toast(error.message)}finally{button.disabled=false}}
async function openMetadataReview(){await Promise.all([loadMetadataReviewQueue(),loadMetadataChangeHistory()]);$('#metadataReviewDialog').showModal()}
async function searchMetadata(w){const queries=[w.originalTitle,w.title].filter((value,index,list)=>value&&list.indexOf(value)===index),responses=await Promise.allSettled(queries.map(query=>fetch(`/api/search?q=${encodeURIComponent(query)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error('metadata');return data.items||[]}))),items=responses.flatMap(result=>result.status==='fulfilled'?result.value:[]);return bestMetadataMatch(items,w)}
async function resolveWorkMetadata(id,w){if(w.year||w._metadataResolving||w._metadataResolved)return;w._metadataResolving=true;try{const matched=await searchMetadata(w);works[id]=matched?{...w,...matched,id,title:w.title||matched.title,creator:w.creator&&w.creator!=='작자 미상'?w.creator:matched.creator,_metadataResolved:true,_metadataResolving:false}:{...w,_metadataResolved:true,_metadataResolving:false};if(current===id)renderWork()}catch{works[id]={...w,_metadataResolved:true,_metadataResolving:false};if(current===id)$('#workYear').textContent='연도 정보 확인 불가'}}
async function loadArtwork(id,w){if(w._artworkLoaded)return;if(artworkCache.has(id)){await artworkCache.get(id);return}const params=new URLSearchParams({title:w.title||'',creator:w.creator||'',mediaType:w.type||w.mediaType||'OTHER',externalId:w.externalId||''}),job=fetch(`/api/artwork?${params}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'artwork');works[id]._artworkLoaded=true;if(data.posterUrl){works[id].posterUrl=data.posterUrl;works[id].artwork={source:data.source,kind:data.kind,selection:data.selection,publisher:data.publisher||null,isbn:data.isbn||null,alternatives:data.alternatives||[]};if(current===id)paintPoster(works[id])}return data}).catch(()=>{works[id]._artworkLoaded=true;return null});artworkCache.set(id,job);await job}
function paintPoster(w){const p=$('#workPoster'),poster=safeUrl(w.posterUrl);p.className='poster '+(poster?'poster-live':(w.poster||'poster-live'));p.style.backgroundImage=poster?`linear-gradient(0deg,rgba(8,10,14,.36),rgba(8,10,14,.02)),url("${poster}")`:'';p.innerHTML=poster?`<span></span><i>${esc(w.year||'')}</i>`:`<span>${esc(w.posterText||w.title)}</span><i>${esc(w.year||'')}</i>`;p.title=w.artwork?.selection||'';p.setAttribute('aria-label',poster?`${w.title} 대표 이미지. ${w.artwork?.selection||'공식 데이터 제공처 이미지'}`:`${w.title} 이미지 준비 중`)}
function renderWork(){const w=works[current];paintPoster(w);$('#workType').textContent=w.type||w.mediaType;$('#workYear').textContent=w.year||'연도 확인 중';const bridge=paintBridgeContext(w);paintPublishers(w);$('.award').textContent=bridge.awards.length?`🏆 ${bridge.awards.join(' · ')}`:w.source||'';$('#workTitle').textContent=w.title;$('#workCreator').textContent=w.creator;const intro=w.quote||w.editorialIntro||w.aiComment||((w.description||'작품 설명이 아직 없습니다.').slice(0,180));$('#workQuote').textContent=`“${intro.replace(/^[“\"]|[”\"]$/g,'')}”`;const dna=w.analysis?.tags?.map(t=>t.tag)||w.tags||[];$('#tasteTags').innerHTML=(dna.length?dna:['Taste DNA 분석 전']).map(t=>`<span class="tag">#${esc(t)}</span>`).join('');$('#saveBtn').classList.toggle('saved',archive.includes(current));$('#saveBtn').innerHTML=archive.includes(current)?'<span>✓</span> 내 성좌에서 빼기':'<span>＋</span> 내 성좌에 담기';renderRecs();loadArtwork(current,w);loadCulturalContext(current,w);loadBookPublishers(current,w);loadEditorialIntro(current,w);resolveWorkMetadata(current,w)}
